# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/wh1100717"
  weibo: "http://weibo.com/yourseric"
  zhihu: "http://www.zhihu.com/people/wh1100717"
  mail: "mailto:me@emptystack.net"
  # twitter: "https://twitter.com/wh1100717"
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #linkedin: "#"

# rss: /atom.xml

subtitle: "I think & code & dream, there I am"

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /img/avatar.png

#你的头像url
avatar: /img/avatar.png 
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: wh1100717
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
# friends:
#   奥巴马的博客: http://localhost:4000/
#   卡卡的美丽传说: http://localhost:4000/

#是否开启“关于我”。
#不开启——
aboutme: http://me.emptystack.net
#开启——
# aboutme: 我是谁，我从哪里来，我到哪里去？我就是我，是颜色不一样的吃货…